plugin:
    name: 'awebsome.products::lang.plugin.name'
    description: 'awebsome.products::lang.plugin.description'
    author: LucasZdv
    icon: oc-icon-briefcase
    homepage: ''

permissions:
    awebsome.products.products:
        tab: 'awebsome.products::lang.plugin.name'
        label: 'Can Manage Products'
