plugin:
    name: 'awebsome.products::lang.plugin.name'
    description: 'awebsome.products::lang.plugin.description'
    author: LucasZdv
    icon: oc-icon-briefcase
    homepage: ''
navigation:
    products:
        label: 'awebsome.products::lang.plugin.name'
        url: awebsome/products/products
        icon: icon-briefcase
        permissions:
            - awebsome.products.products
        sideMenu:
            products:
                label: 'awebsome.products::lang.plugin.name'
                url: awebsome/products/products
                icon: icon-briefcase
                permissions:
                    - awebsome.products.products
permissions:
    awebsome.products.products:
        tab: 'awebsome.products::lang.plugin.name'
        label: 'Can Manage Products'
